# Generated by Django 4.1.3 on 2022-12-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='agreeable_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='disagreeable_num',
            field=models.IntegerField(default=0),
        ),
    ]
